### PR TITLE
Corrected a few typos

### PR DESCRIPTION
**Pull request by jamiekt**
Hi Rui,
A few very inconsequential changes here. Basically just correcting a few typos in the comments

### CODE REVIEW

**Comment by jamiekt** [comment]
Adding more commits to this pull request. Previously github was treating the files as binary files (I think because they had a BOM embedded in there somewhere). Corrected herein.
Github should now be able to show differences between versions and viewing using the "raw" button should work properly (it wasn't doing before)

**Comment by jamiekt** [comment]
Further correction to ensure script runs correctly.

**Comment by RuiRomano** [comment]
Hi Jamie, thank you for the PR, but I'm still not able to show the diferences between your commits and the main branch...

**Comment by jamiekt** [comment]
Hi Rui,
Perhaps that's because the files in the main branch are, at this time, still binary. To demonstrate, here's the raw view of PowerBIPS.psmi in your branch: (https://raw.githubusercontent.com/DevScope/powerbi-powershell-modules/master/Modules/PowerBIPS/PowerBIPS.psm1) and here it is in my branch: (https://raw.githubusercontent.com/jamiekt/powerbi-powershell-modules/master/Modules/PowerBIPS/PowerBIPS.psm1)

Regards
Jamie

**Comment by RuiRomano** [comment]
That makes perfect sense, just made the merge. Keep it coming... ;)

**Comment by jamiekt** [comment]
Will do. I'm a big fan of unit testing PowerShell using [Pester](https://github.com/pester/Pester) so might be contributing some of those soon.

**Comment by RuiRomano** [comment]
I'm a fan of unit testing too ;) I had seen Pester but never give it a try :(... So if you have the time to submit a Pester test would be great!

**Comment by jamiekt** [comment]
Sure, will try and find the time soon. I've done quite a bit of work with Pester over the past 9 months so hopefully can contribute quite a bit in this area (just a matter of finding the time).

**Pull request merged**
