### PR TITLE
including the Microsoft.IdentityModel.Clients.ActiveDirectory.dll

### PR DESCRIPTION
**Pull request by Stijnc**
As discussed a pull request where an automatic download of the Microsoft.IdentityModel.Clients.ActiveDirectory.dll is not needed anymore.
I included the dll as a required pre-reg in the module manifest and made the required changes in de psm1 file.

I also included a automation.json file in so once the file is imported into Azure Automation a specific powerBI automation connection asset is available.

### CODE REVIEW

**Comment by RuiRomano** [comment]
Hi Stinjnc,

I was trying to merge your commit but got some conflicts...

Your branch dont have the changes made by "mattmcnabb" (-credential param), can you please sync with the last version and make another commit?

Thanks

**Comment by Stijnc** [comment]
merged with latest master as requested

**Comment by RuiRomano** [comment]
Hi Stijnc, merged into master.

One question, what's the need of Modules\PowerBIPS.zip?

Thanks

**Comment by Stijnc** [comment]
you can remove the zip file. 
Azure automation expects a zip file ( I used it when testing)

**Comment by RuiRomano** [comment]
Done.

**Pull request merged**
